# SPDX-License-Identifier: MIT
"""Build script for the beamgrad Python package (metadata lives in pyproject.toml).

Extensions:
  beamgrad._C       CPU operators (always built)
  beamgrad._C_cuda  CUDA operators; BEAMGRAD_CUDA=auto (default) builds them
                    when a CUDA-enabled PyTorch and a CUDA toolkit of the same
                    major version are present, and otherwise (or if they fail
                    to compile) warns and builds without them; 1 requires them,
                    0 skips them. TORCH_CUDA_ARCH_LIST selects GPU
                    architectures.
  beamgrad._libdbs  the plain C library, loaded with ctypes (JAX integration)

The compiled operators only work with the PyTorch they were built against, so
the build records its version in beamgrad/_build_info.py, which beamgrad checks
at import time. They do not depend on the Python version: they use only
CPython's limited API, so wheels are tagged cp310-abi3.

Release wheels (see .github/workflows/wheels.yml) set:
  BEAMGRAD_PIN_TORCH=1          require the PyTorch minor version built against
  BEAMGRAD_LOCAL_VERSION=pt214cu126   append a local version label (+pt214cu126)
"""

import os
import re
import subprocess
import sys
from pathlib import Path

import torch
from setuptools import Extension, setup
from torch.utils.cpp_extension import CUDA_HOME, BuildExtension, CppExtension, CUDAExtension

ROOT = Path(__file__).resolve().parent
CORE_SOURCES = sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / "src").glob("*.cpp"))
INCLUDE_DIRS = [str(ROOT / "include"), str(ROOT / "src")]
WINDOWS = sys.platform == "win32"
# The torch extensions use whatever C++ standard PyTorch requires (added by
# BuildExtension); the core itself is C++17 and builds under C++17 or later.
# No floating-point contraction: results must not depend on the target (MSVC
# does not contract by default).
CXX_FLAGS = ["/O2"] if WINDOWS else ["-O3", "-ffp-contract=off"]
CXX17_FLAGS = CXX_FLAGS + (["/std:c++17"] if WINDOWS else ["-std=c++17", "-fvisibility=hidden"])
# CPython's stable ABI, as of the oldest supported Python (3.10).
LIMITED_API = [("Py_LIMITED_API", "0x030A0000")]


def enabled(name: str) -> bool:
    return os.environ.get(name, "0").strip().lower() in {"1", "on", "true", "yes"}


def package_version() -> str:
    version = (ROOT / "VERSION").read_text().strip()
    local = os.environ.get("BEAMGRAD_LOCAL_VERSION", "").strip()
    return f"{version}+{local}" if local else version


def requirements() -> list[str]:
    if not enabled("BEAMGRAD_PIN_TORCH"):
        return ["torch>=2.4"]
    major, minor = torch.__version__.split("+")[0].split(".")[:2]
    return [f"torch=={major}.{minor}.*"]


def write_build_info(
    cuda_skipped: str | None = None, path: Path = ROOT / "python" / "beamgrad" / "_build_info.py"
) -> None:
    abi = getattr(torch._C, "_GLIBCXX_USE_CXX11_ABI", None)
    text = (
        "# Generated by setup.py: the PyTorch the compiled extensions were built against.\n"
        f"TORCH_VERSION = {torch.__version__!r}\n"
        f"TORCH_CUDA_VERSION = {torch.version.cuda!r}\n"
        f"CXX11_ABI = {abi!r}\n"
        "# Why the CUDA operators were not built, when BEAMGRAD_CUDA=auto left them out.\n"
        f"CUDA_SKIPPED = {cuda_skipped!r}\n"
    )
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


CUDA_MODE = os.environ.get("BEAMGRAD_CUDA", "auto").strip().lower()
CUDA_EXTENSION = "beamgrad._C_cuda"
WITHOUT_CUDA = (
    "Building beamgrad without its CUDA operators (CUDA tensors will not be supported). Prebuilt wheels "
    "for each PyTorch and CUDA version are listed in docs/installation.md; set BEAMGRAD_CUDA=1 to make "
    "this an error, or BEAMGRAD_CUDA=0 to skip CUDA without a warning."
)


CUDA_SKIPPED: str | None = None  # recorded in _build_info.py


def skip_cuda(reason: str) -> None:
    global CUDA_SKIPPED
    CUDA_SKIPPED = reason
    print(f"WARNING: {reason} {WITHOUT_CUDA}", file=sys.stderr)


def nvcc_version() -> str | None:
    """The CUDA version of CUDA_HOME's nvcc, e.g. "12.4", or None if it cannot be run."""
    nvcc = Path(CUDA_HOME) / "bin" / ("nvcc.exe" if WINDOWS else "nvcc")
    try:
        out = subprocess.run([str(nvcc), "--version"], capture_output=True, text=True, timeout=120).stdout
    except (OSError, subprocess.SubprocessError):
        return None
    match = re.search(r"release (\d+)\.(\d+)", out)
    return f"{match.group(1)}.{match.group(2)}" if match else None


def build_cuda() -> bool:
    if CUDA_MODE in {"0", "off", "false", "no"}:
        return False
    toolkit = CUDA_HOME is not None and torch.version.cuda is not None
    if CUDA_MODE in {"1", "on", "true", "yes"}:
        if not toolkit:
            raise RuntimeError(
                "BEAMGRAD_CUDA=1 requires a CUDA-enabled PyTorch and a CUDA toolkit (nvcc); "
                "set CUDA_HOME if it is not found."
            )
        return True
    if CUDA_MODE != "auto":
        raise RuntimeError(f"BEAMGRAD_CUDA must be auto, 0 or 1, got {CUDA_MODE!r}")
    if torch.version.cuda is None:
        return False  # a CPU-only PyTorch: nothing to build
    if CUDA_HOME is None:
        skip_cuda(f"PyTorch uses CUDA {torch.version.cuda}, but no CUDA toolkit was found (set CUDA_HOME).")
        return False
    found = nvcc_version()
    if found is None:
        skip_cuda(f"nvcc under CUDA_HOME={CUDA_HOME} could not be run.")
        return False
    # PyTorch refuses to build an extension with a toolkit of another major version.
    if found.split(".")[0] != torch.version.cuda.split(".")[0]:
        skip_cuda(
            f"The CUDA toolkit at CUDA_HOME={CUDA_HOME} is CUDA {found}, but PyTorch was built with CUDA "
            f"{torch.version.cuda}; point CUDA_HOME at a CUDA {torch.version.cuda.split('.')[0]}.x toolkit to "
            "build the CUDA operators."
        )
        return False
    return True


class BuildExt(BuildExtension):
    """With BEAMGRAD_CUDA=auto, a build that fails while the CUDA extension is part
    of it (PyTorch rejects the host compiler for this CUDA version, or nvcc fails)
    is retried without that extension, with a warning, instead of failing the whole
    installation. A failure of the CPU-only build is still an error."""

    def build_extensions(self):
        cuda = [ext for ext in self.extensions if ext.name == CUDA_EXTENSION]
        if not cuda or CUDA_MODE != "auto":
            return super().build_extensions()
        try:
            return super().build_extensions()
        except Exception as exc:
            first_line = str(exc).strip().splitlines()[0].rstrip(".") if str(exc).strip() else type(exc).__name__
            skip_cuda(f"Building the CUDA operators failed ({first_line}).")
        self.extensions.remove(cuda[0])
        super().build_extensions()
        # build_py has already copied _build_info.py into the build tree: update both copies.
        write_build_info(CUDA_SKIPPED)
        built = Path(self.build_lib) / "beamgrad" / "_build_info.py"
        if built.exists():
            write_build_info(CUDA_SKIPPED, built)


ext_modules = [
    CppExtension(
        "beamgrad._C",
        ["python/csrc/cpu_ops.cpp", *CORE_SOURCES],
        include_dirs=INCLUDE_DIRS,
        define_macros=LIMITED_API,
        extra_compile_args={"cxx": CXX_FLAGS},
        py_limited_api=True,
    ),
    Extension(
        "beamgrad._libdbs",
        ["python/csrc/libdbs_module.cpp", *CORE_SOURCES],
        include_dirs=INCLUDE_DIRS,
        define_macros=[("DBS_BUILD_SHARED", "1"), ("DBS_COMPILING_LIBRARY", "1"), *LIMITED_API],
        extra_compile_args=CXX17_FLAGS,
        language="c++",
        py_limited_api=True,
    ),
]

if build_cuda():
    ext_modules.append(
        CUDAExtension(
            CUDA_EXTENSION,
            ["python/csrc/cuda_ops.cpp", "cuda/dbs_cuda.cu"],
            include_dirs=INCLUDE_DIRS,
            define_macros=LIMITED_API,
            extra_compile_args={"cxx": CXX_FLAGS, "nvcc": ["-O3"]},
            py_limited_api=True,
        )
    )

write_build_info(CUDA_SKIPPED)
setup(
    version=package_version(),
    install_requires=requirements(),
    ext_modules=ext_modules,
    cmdclass={"build_ext": BuildExt},
    options={"bdist_wheel": {"py_limited_api": "cp310"}},
)
