# SPDX-License-Identifier: MIT
"""Build script for the beamgrad Python package (metadata lives in pyproject.toml).

Extensions:
  beamgrad._C       CPU operators (always built)
  beamgrad._C_cuda  CUDA operators; BEAMGRAD_CUDA=auto (default) builds them
                    when a CUDA toolkit and a CUDA-enabled PyTorch are present,
                    1 requires them, 0 skips them. TORCH_CUDA_ARCH_LIST selects
                    GPU architectures.
  beamgrad._libdbs  the plain C library, loaded with ctypes (JAX integration)

The compiled operators only work with the PyTorch they were built against, so
the build records its version in beamgrad/_build_info.py, which beamgrad checks
at import time. They do not depend on the Python version: they use only
CPython's limited API, so wheels are tagged cp310-abi3.

Release wheels (see .github/workflows/wheels.yml) set:
  BEAMGRAD_PIN_TORCH=1          require the PyTorch minor version built against
  BEAMGRAD_LOCAL_VERSION=pt214cu126   append a local version label (+pt214cu126)
"""

import os
import sys
from pathlib import Path

import torch
from setuptools import Extension, setup
from torch.utils.cpp_extension import CUDA_HOME, BuildExtension, CppExtension, CUDAExtension

ROOT = Path(__file__).resolve().parent
CORE_SOURCES = sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / "src").glob("*.cpp"))
INCLUDE_DIRS = [str(ROOT / "include"), str(ROOT / "src")]
WINDOWS = sys.platform == "win32"
# The torch extensions use whatever C++ standard PyTorch requires (added by
# BuildExtension); the core itself is C++17 and builds under C++17 or later.
# No floating-point contraction: results must not depend on the target (MSVC
# does not contract by default).
CXX_FLAGS = ["/O2"] if WINDOWS else ["-O3", "-ffp-contract=off"]
CXX17_FLAGS = CXX_FLAGS + (["/std:c++17"] if WINDOWS else ["-std=c++17", "-fvisibility=hidden"])
# CPython's stable ABI, as of the oldest supported Python (3.10).
LIMITED_API = [("Py_LIMITED_API", "0x030A0000")]


def enabled(name: str) -> bool:
    return os.environ.get(name, "0").strip().lower() in {"1", "on", "true", "yes"}


def package_version() -> str:
    version = (ROOT / "VERSION").read_text().strip()
    local = os.environ.get("BEAMGRAD_LOCAL_VERSION", "").strip()
    return f"{version}+{local}" if local else version


def requirements() -> list[str]:
    if not enabled("BEAMGRAD_PIN_TORCH"):
        return ["torch>=2.4"]
    major, minor = torch.__version__.split("+")[0].split(".")[:2]
    return [f"torch=={major}.{minor}.*"]


def write_build_info() -> None:
    abi = getattr(torch._C, "_GLIBCXX_USE_CXX11_ABI", None)
    text = (
        "# Generated by setup.py: the PyTorch the compiled extensions were built against.\n"
        f"TORCH_VERSION = {torch.__version__!r}\n"
        f"TORCH_CUDA_VERSION = {torch.version.cuda!r}\n"
        f"CXX11_ABI = {abi!r}\n"
    )
    path = ROOT / "python" / "beamgrad" / "_build_info.py"
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


def build_cuda() -> bool:
    mode = os.environ.get("BEAMGRAD_CUDA", "auto").strip().lower()
    if mode in {"0", "off", "false", "no"}:
        return False
    toolkit = CUDA_HOME is not None and torch.version.cuda is not None
    if mode in {"1", "on", "true", "yes"}:
        if not toolkit:
            raise RuntimeError(
                "BEAMGRAD_CUDA=1 requires a CUDA-enabled PyTorch and a CUDA toolkit (nvcc); "
                "set CUDA_HOME if it is not found."
            )
        return True
    if mode != "auto":
        raise RuntimeError(f"BEAMGRAD_CUDA must be auto, 0 or 1, got {mode!r}")
    return toolkit


ext_modules = [
    CppExtension(
        "beamgrad._C",
        ["python/csrc/cpu_ops.cpp", *CORE_SOURCES],
        include_dirs=INCLUDE_DIRS,
        define_macros=LIMITED_API,
        extra_compile_args={"cxx": CXX_FLAGS},
        py_limited_api=True,
    ),
    Extension(
        "beamgrad._libdbs",
        ["python/csrc/libdbs_module.cpp", *CORE_SOURCES],
        include_dirs=INCLUDE_DIRS,
        define_macros=[("DBS_BUILD_SHARED", "1"), ("DBS_COMPILING_LIBRARY", "1"), *LIMITED_API],
        extra_compile_args=CXX17_FLAGS,
        language="c++",
        py_limited_api=True,
    ),
]

if build_cuda():
    ext_modules.append(
        CUDAExtension(
            "beamgrad._C_cuda",
            ["python/csrc/cuda_ops.cpp", "cuda/dbs_cuda.cu"],
            include_dirs=INCLUDE_DIRS,
            define_macros=LIMITED_API,
            extra_compile_args={"cxx": CXX_FLAGS, "nvcc": ["-O3"]},
            py_limited_api=True,
        )
    )

write_build_info()
setup(
    version=package_version(),
    install_requires=requirements(),
    ext_modules=ext_modules,
    cmdclass={"build_ext": BuildExtension},
    options={"bdist_wheel": {"py_limited_api": "cp310"}},
)
